on:
  push:
  workflow_dispatch:

name: test_env

jobs:
  test_env:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: macOS-12}
        - {os: windows-latest}
        - {os: ubuntu-latest}
        - {os: macos-14}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      _R_CHECK_FORCE_SUGGESTS_: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up miniforge and build environment (non-Windows)
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: ./env_r432
          environment-file: env_r432.yaml

      - name: List content of environment
        run: conda list -p ./testenv

